Dynamic import support
[dynamic import](https://github.com/tc39/proposal-dynamic-import) support has just landed in [Rollup 0.55.0](https://github.com/rollup/rollup/blob/master/CHANGELOG.md#upcoming-0550).
When testing a project that uses nodent via rollup-plugin-nodent, I noticed that it doesn't support dynamic import yet, resulting in the error

```
SyntaxError: Unexpected token in ...
```

Looking at the [rollup source code](https://github.com/rollup/rollup/blob/089c9e06190b894d766fc44571752fa91dc1eaa5/src/Graph.ts#L3), I see that they are using [acorn-dynamic-import](https://github.com/kesne/acorn-dynamic-import).
This patches the acorn version that is used in nodent to add the acorn-dynamic-import plugin as done in rollup itself.
That way, the nodent compiler is able to parse code that uses dynamic import.

This is quite similar to what has been done for [buble](https://github.com/Rich-Harris/buble/pull/102).

Also switch from xo to eslint and eslint-config/plugin-*